### ISSUE TITLE
本リリースレビュー依頼

### ISSUE THREAD

**Issue by daichi3102** [daichi3102/wordpass#117]
### MeigenOtter
名言提供アプリ
https://wordpass-ldtw.onrender.com/

## 実装した機能
- [x] ユーザー登録機能
- [x] ログイン機能
- [x] Googleログイン機能
- [x] 名言取得機能 ※未ログイン可
- [x] 名言取得結果のXへのシェア機能 ※未ログイン可
- [x] 名言取得結果の保存機能 ※未ログイン可
- [x] プロフィール機能
- [x] 名前変更機能
- [x] メールアドレス変更機能
- [x] アバター変更機能
- [x] 条件を指定した名言取得機能
- [x] 条件を指定した名言取得結果の削除機能
- [x] 条件を指定した名言取得結果のXシェア機能
- [x] 名言作成機能（投稿機能）
- [x] 名言作成削除機能
- [x] 名言作成編集機能
- [x] 名言作成一覧機能
- [x] 名言作成いいね機能
- [x] いいねした名言一覧機能
### MVP後に追加した機能
- [x] いいねのカウント機能
- [x] マイページ機能
- [x] マイページからのプロフィール編集機能
- [x] マイページからのAIから受け取った名言一覧機能
- [x] マイページからの作成した名言一覧機能
- [x] マイページからのいいねした名言一覧機能
- [x] 作成された名言のXシェア機能
- [x] エラーページの作成
- [x] ファビコンの作成
- [x] 条件を指定した名言取得機能で選択した値がプレースフォルダーとして残る
## 今後追加したい機能
- [ ] パスワードリセット機能
- [ ] アプリ内通知機能

## サービスイメージがわかるようなスクリーンショット等
- [x] パーソナライズした名言取得機能
![MOai](https://github.com/daichi3102/wordpass/assets/149915927/3eb00a0a-75f8-4592-9209-1ec83e45972e)

- [x] 名言作成機能
![MOmake](https://github.com/daichi3102/wordpass/assets/149915927/47b42b56-092b-425b-8821-02457d2e2bd3)

※ユーザーは、上の句のみ、下の句のみ、もしくは両方を選び、名言を投稿できる
※上の句の場合は、他ユーザーもしくは自分自身が後から下の句を追加可能
※下の句の場合は、他ユーザーもしくは自分自身が後から上の句を追加可能
※両方選んだ場合は、自分自身しか編集、削除などを行えない

**Comment by Tsuchiya2** [comment]
ご提出ありがとうございます！
以下、サービスを触ってのレビューになります。
よりよいアプリケーションにするために、もうひと頑張りです！

---

■renderの有料化
・URLをクリックしてからページが表示されるまでに時間がかかっているため、renderの有料化を行ってすぐにトップページが開くようにしましょう。

■独自ドメイン
・独自ドメインを取得して反映しましょう。

■アカウント登録後の画面
・アカウント登録後、以下の画面に遷移しますが、パッと見た際にまだ何も操作していないのに、LINEのような投稿のやりとりしたような画面が出てしまっているので、ユーザーを困惑させてしまう体験になっているかと感じました。
![image](https://github.com/daichi3102/wordpass/assets/61481161/a6e58d65-7311-456d-8969-3956715d5583)

■ログイン後の左上のロゴをクリックした際の遷移
・このサービス、マイページ（ログイン後のトップページ）・名言を受け取る・名言を作るの3つが主要なページかと思いますが、名言作成からトップページへ遷移しようとロゴをクリックすると、LPページに遷移してしまい、ユーザーが想像している動線との乖離がありそうです。ユーザー体験を向上するためにも、ユーザーを困惑させないUI/UXを意識して改善しましょう。

■ヘッダーの整理
・現状「名言を受け取る」「名言を作る」となっていますが、内容を見ると"AI"と"人間"に分かれているのが実情かと思うので、こちらもユーザーに？？と思わせないように優しく・分かりやすく・実状に即したメニューに整えてユーザー体験を向上させましょう。

■みんなの作成した名言一覧
・縦にズラッと並べてしまっているので、PCサイズだと全部を見る際にだいぶスライドしないといけないためユーザー体験としてはあまり良い体験になっていないように感じました。レスポンス対応して横幅に応じて1行に表示される数を変化させるなどしてあげましょう。また、スマホでも投稿が多くなってきた際に毎回だいぶスライドしないと過去の名言が確認できないので、ページネーションを導入してユーザー体験を向上させましょう。

■使用する色
・成功時のフラッシュメッセージですが、世界観からするとやや浮き気味に感じたので、ブルー系の色（Xシェアと同じ色でもいいかも）で統一感を出した方がよいかもと思いました。ご検討ください。
・イイネの☆も黄色系にサれていますが、見づらいため、世界観統一の観点からもブルー系（やや濃い目など？）にするとよいかと思いました。ご検討ください。

■AIから受け取った名言一覧
![image](https://github.com/daichi3102/wordpass/assets/61481161/ab7c364f-9dfd-4280-8ac1-155716e35c16)
・詳細を見るをクリックして一覧に表示されていない詳細な情報が見れるかとユーザーが期待してクリックした際に、一覧画面で表示されていた内容と同じものが表示されているページに遷移するのであれば、詳細ページを無くして、一覧ページで「Xシェア」「削除する」を行えるようにしましょう。詳細ページに表示される「もう一度受け取る」ですが、"新しくAIから名言を受け取る"かと思うので、ユーザーが期待する表示されている名言に関連した名言を受け取るでは無さそうなので、一覧ページに集約した際はページ上部もしくはヘッダーに新規AI名言作成の動線があるので不要かもと感じました。ご検討ください。

■AIから名言を受け取る・AIから受け取った名言一覧
・実状は「名言の自動生成」「自動生成名言一覧」かと思うので、文言もユーザーに優しく・分かりやすく・実状に即したものに修正していくと、ユーザー体験が向上するかと思います。

■AIが名言作成している間の待ち時間
・AIが名言を作成している間、ローディング画面を挟むとユーザー体験を向上できるかと思います。ローディング画面はAIが名言を作成しているアニメーションなど、世界観に即したものであるとよりGoodです。

■テストを書く
・RSpecを用いて、モデルテスト・システムテストを書きましょう。

■makes/id ページ
・URL直打ちすると、他者の投稿した名言の詳細ページが開いて"編集する"ボタンが押せてしまうため、投稿関係者以外はアクセスできないように配慮してあげておくと、細かい部分もケアしていてよいかと思います。

■Rubocop
・できるだけ素のRubocopを通してコードをキレイに保ちましょう。

■余計なファイルの削除
・0や12288など使用していないファイルやフォルダは削除しましょう。

■CI(GitHubActions)の導入
・pushされた際にGitHubActionsが動いてRubocopが自動でチェックが入るようにしましょう。また、RSpecも書いたらそちらも導入しましょう。

■検索機能の導入
・名言の投稿が増えていくにつれて、出会いたい名言に出会うまでが困難になっていくかと思います。シチュエーションや分類などから探している名言を見つけられるようにしてあげるとユーザー体験が向上するかと思います。

---

結構な数コメントしてしまったので、一旦ここまででお返しさせていただきますね。
上記、issue化してProjectsに反映してもらい、いつ頃に再レビュー依頼を出せそうかをスレッドの方にメンションを付けてご連絡いただけますでしょうか。

引き続きよろしくお願いいたします。

**Comment by daichi3102** [comment]
## 各種情報
### MeigenOtter
名言提供アプリ
https://meigenotter.com/

## 本リリース中間レビュー依頼までに実装した機能
- [x] ユーザー登録機能
- [x] ログイン機能
- [x] Googleログイン機能
- [x] AIからの名言取得機能 ※未ログイン可
- [x] AIからの名言取得結果のXへのシェア機能 ※未ログイン可
- [x] AIからの名言取得結果の保存機能 ※未ログイン可
- [x] プロフィール機能
- [x] 名前変更機能
- [x] メールアドレス変更機能
- [x] アバター変更機能
- [x] 条件を指定したAIからの名言取得機能
- [x] 条件を指定したAIからの名言取得結果の削除機能
- [x] 条件を指定したAIからの名言取得結果のXシェア機能
- [x] 名言作成機能（投稿機能）
- [x] 名言作成削除機能
- [x] 名言作成編集機能
- [x] 名言作成一覧機能（全ユーザー）
- [x] 名言作成いいね機能
- [x] いいねのカウント機能
- [x] マイページ機能
- [x] マイページからのプロフィール編集機能
- [x] マイページからのAIから受け取った名言一覧機能
- [x] マイページからの作成した名言一覧機能
- [x] マイページからのいいねした名言一覧機能
- [x] 作成された名言のXシェア機能
- [x] エラーページの作成
- [x] ファビコンの作成
- [x] 条件を指定した名言取得機能で選択した値がプレースフォルダーとして残る

## 本リリース中間レビュー依頼後に実装した機能
- [ ] AIからの名言取得一覧機能（全ユーザー）
- [ ] AIからの名言取得一覧ページでのページネーション
- [ ] AIからの名言取得一覧ページでの検索機能
- [ ] AIからの名言取得時のローディングモーダルの追加
- [ ] 名言作成一覧ページでのページネーション
- [ ] 名言作成一覧ページでの削除機能
- [ ] 名言作成一覧ページでの編集機能
- [ ] 名言作成一覧ページでの検索機能
- [ ] マイページのタブの非同期化
- [ ] Rubocopの導入
- [ ] RSpecの導入
- [ ] Webサービス有料化による通信速度の改善
- [ ] 独自ドメインの取得

## 確認、変更ポイント
- [ ] AIからの名言取得一覧では、全ユーザーの取得した名言が表示されるようにしました
- [ ] AIからの名言取得結果ページでの『もう一度受け取る』という文言を『AIから受け取る』に変更しました
- [ ] 名言作成詳細ページの削除しました
- [ ] 名言作成一覧ページから詳細ページ行っていたものをできるようにしました
- [ ] ヘッダーの文言の修正をしました（AIと人間の違い）
- [ ] フラッシュメッセージの色の変更（緑から水色）をしました
- [ ] アカウント登録後にトップページに画面遷移すること
- [ ] make/id直打ちでのアクセスを制限しました
- [ ] Rubocopのテストを通しました
- [ ] RSpecのテストを通しました
- [ ] 余計なファイルを削除しました

## コメント
- [ ] いいねの星の色に関しては、こだわりがあったため黄色のままにしました
- [ ] 各一覧ページでは、各名言をデスクトップサイズでも横に２列にはせず、ページネーションと検索機能で対応しました
- [ ] AIからの名言取得一覧ページでの検索機能は、moodとquote typeカラムに対してのプルダウン式の検索と、responseカラムに対してのフリワード検索にしました
- [ ] 名言作成一覧ページでの検索機能は、上の句と下の句のテーブルのcontentカラムと、ユーザーテーブルのnameカラムに対してのフリーワード検索にしました

## 今後追加したい機能
- [ ] パスワードリセット機能
- [ ] アプリ内通知機能

## サービスイメージがわかるようなスクリーンショット等
- [x] AIからの名言取得時のモーダル
![a1724928a683bdf60b595f59ac80cc8b](https://github.com/daichi3102/wordpass/assets/149915927/52e46bb9-0dec-4554-aa54-ec1609a9cba0)

- [x] AIからの名言取得一覧ページでの検索機能
![408b5c0cf9886c638821ef2b70888568](https://github.com/daichi3102/wordpass/assets/149915927/8901f547-68a6-4d6f-8869-f5fb1b6932df)

- [x] 名言作成一覧ページでの検索機能
![5459daa0a4c91cb4d13591a07e8f10ff](https://github.com/daichi3102/wordpass/assets/149915927/f391fc6b-3d97-4917-8255-8940c3d5f584)

**Comment by Tsuchiya2** [comment]
ありがとうございます。
以下サービス、コードを見てのコメントになります。
就活の準備と並行して対応していきましょう！

---

■使っていないファイルの削除
・feature_errorpage, testフォルダ, :q,error404.html.erb, ....その他諸々、不要なファイルはGitHubに挙げないようにしましょう！

■CI通過状態に保つ
・通過していない状態だと印象が悪くなってしまいます。グリーン状態にしておくのと、spec/配下ではなく、wordpass/配下でCIの◯✗が表示されるようにしておくと、パッと見た際にCIを導入していることが伝わります。

![image](https://github.com/daichi3102/wordpass/assets/61481161/72fecdde-3f20-429b-bea3-b5e8f42255d3)

■scope, クラスメソッドを活用する
・first_parts_controller.rbのFirstPart.joins... の部分など scopeやクラスメソッドを使った記載にして可読性の高いコードにしましょう。

■Rubocop
・素のRubocopが通るようにコードをリファクタリングしていきましょう。
