### ISSUE TITLE
MVPレビュー依頼

### ISSUE THREAD

**Issue by daichi3102** [daichi3102/wordpass#85]
### MeigenOtter
名言提供アプリ
https://wordpass-ldtw.onrender.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] ユーザー登録機能
- [x] ログイン機能
- [x] googleログイン機能
- [ ] パスワードリセット機能
- [x] 診断機能（名言取得機能に変更）※未ログイン可
- [x] 診断結果（名言取得結果に変更）のXへのシェア機能※未ログイン可
- [x] 診断結果（名言取得結果に変更）の保存機能※未ログイン可
- [x] プロフィール機能
- [x] 名前変更機能
- [x] メールアドレス変更機能
- [ ] プロフィールページでの診断履歴一覧機能
- [ ] プロフィールページでの診断履歴の公開、非公開機能
- [ ] プロフィールページでの診断履歴の削除機能
- [ ] 他のユーザーの診断履歴一覧機能
- [ ] 掲示板投稿機能（名言募集機能）
- [ ] プロフィールページでの掲示板投稿一覧機能
- [ ] プロフィールページでの掲示板投稿詳細機能
- [ ] プロフィールページでの掲示板投稿詳細からの投稿編集機能
- [ ] プロフィールページでの掲示板投稿詳細からの投稿削除機能
- [ ] 他のユーザーの掲示板投稿一覧機能
- [ ] 他のユーザーの掲示板投稿詳細での回答一覧機能
- [ ] 他のユーザーの掲示板投稿詳細での回答機能（名言回答機能）
- [ ] プロフィールページでの掲示板投稿詳細からの回答編集機能
- [ ] プロフィールページでの掲示板投稿詳細からの回答削除機能

### 減らした機能
- [ ] パスワードリセット機能
- [ ] プロフィールページでの診断履歴の公開、非公開機能
- [ ] 他のユーザーの診断履歴一覧機能
- [ ] 掲示板投稿機能（名言募集機能）
- [ ] プロフィールページでの掲示板投稿一覧機能
- [ ] プロフィールページでの掲示板投稿詳細機能
- [ ] プロフィールページでの掲示板投稿詳細からの投稿編集機能
- [ ] プロフィールページでの掲示板投稿詳細からの投稿削除機能
- [ ] 他のユーザーの掲示板投稿一覧機能
- [ ] 他のユーザーの掲示板投稿詳細での回答一覧機能
- [ ] 他のユーザーの掲示板投稿詳細での回答機能（名言回答機能）
- [ ] プロフィールページでの掲示板投稿詳細からの回答編集機能
- [ ] プロフィールページでの掲示板投稿詳細からの回答削除機能

### 増やした機能
- [x] パーソナライズした名言取得機能
- [x] パーソナライズした名言取得結果の削除機能
- [x] パーソナライズした名言取得結果のXシェア機能
- [x] 名言作成機能（投稿機能）
- [x] 名言作成削除機能
- [x] 名言作成編集機能
- [x] 名言作成一覧機能
- [x] 名言作成いいね機能（お気に入り）
- [x] いいねした名言一覧機能
--
※ユーザーは、上の句のみ、下の句のみ、もしくは両方を選び、名言を投稿できる
※上の句の場合は、他ユーザーもしくは自分自身が後から下の句を追加可能
※下の句の場合は、他ユーザーもしくは自分自身が後から上の句を追加可能
※両方選んだ場合は、自分しか編集、削除などを行えない

## サービスイメージがわかるようなスクリーンショット等
- [x] パーソナライズした名言取得機能
![e3f2e8525a395b1c3035f65f41892a1f](https://github.com/daichi3102/wordpass/assets/149915927/c07ecc42-0257-4a1c-8934-bbf0a6e35e7d)

- [x] 名言作成機能
![17222b6c6c3bd364f6e8a9c607c375b5](https://github.com/daichi3102/wordpass/assets/149915927/1fd8fafc-3acc-4972-9c24-af489d17b4b5)

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。

**Comment by daichi3102** [comment]
添削いただき、ありがとうございます。
引き続き修正や機能追加、頑張っていきます。
